### ISSUE TITLE
Submit ebdb to PyPi (sdist)

### ISSUE THREAD

**Issue by koobs** [sassoftware/epdb#1]
Submitting to PyPi will ensure that the 'epdb' package name is reserved, and that the package is installable via pip/easy_install/etc

Please include (in the sdist):
- LICENCE file
- Test suite/files (if present)

**Comment by mikjo** [comment]
https://pypi.python.org/pypi/epdb/ has been there for years, and points to this repository. It has an .egg for download.

**Comment by koobs** [comment]
@mikjo This request is for a source distribution (sdist upload)
