### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by MageMasher** [sassoftware/epdb#4]
This looks like an interesting project but I have no idea how to use it. 

Where can I start learning about epdb?

**Comment by mibanescu** [comment]
Valid point. We will add some documentation in the near future. In short, you can use it just like pdb, but you have some extra commands: ability to set conditional break points, trace conditions, remote debugging via serve()/connect(), printing the stack's content etc.

**Comment by kamikaze** [comment]
interested in this too

**Comment by wfscheper** [comment]
@MageMasher and @kamikaze:

Did the updates to the README in 040e87fdc624011b902876329f4e0028aba40876 address your documentation questions?
