### ISSUE TITLE
Trying to use this on macbook

### ISSUE THREAD

**Issue by mikewiebe** [sassoftware/epdb#6]
I use epdb to debug ansible modules on my Ubuntu server without any problems but I can't seem to get it to work on my mac.  I am hoping someone maintaining this project can give me some ideas.

When I connect to `localhost 8080` it connects but then just hangs.

```
Connected to localhost.
Escape character is '^]'.
```
I have tried playing with the telnet mode to make sure it is set to `character`  but I don't get the epdb debug shell.

**Comment by wfscheper** [comment]
Hey @mikewiebe, do you know what version of python you're using on your mac? Also are you connecting to epdb via telnet from the command line or via something like `python -c 'import epdb; epdb.connect()'`?

**Comment by mikewiebe** [comment]
Hi @wfscheper, Thanks for the quick reply!

`Python Version: Python 2.7.11`

I started with `python -c 'import epdb; epdb.connect()` since that is how I used it in my Ubuntu environment but when that hung I switched to `telnet localhost 8080` from the mac terminal so that I could play with the telnet options.

**Comment by wfscheper** [comment]
Forgot to ask, do you know what version of epdb you're using and how it was installed (pip, python setup.py, easy_install, etc)? Also is python the system python or did you install py27 from some other source?

Hopefully this will help me recreate the issue for debugging, as this isn't something I've seen before.

**Comment by mikewiebe** [comment]
@wfscheper Ok, your questions helped me work through some of the mess that is/was python setup on my mac!  I had the system version of python of course but I was using a version that I installed a long time ago but I don't  remember exactly how I installed it.

Long story short, I re-installed python (version 2.7.13 and 3.5.0) using `Homebrew` and then setup python virtual environments.  From the 2.7.13 virtual env, `epdb` is now working as expected!

I did notice that the latest version of `epdb-0.15` supports python 3 but I am having trouble installing it.

```
(ansible-py3) mwiebe:Virtualenvs mwiebe$ pip install epdb==0.15
Collecting epdb==0.15
  Could not find a version that satisfies the requirement epdb==0.15 (from versions: 0.12)
No matching distribution found for epdb==0.15
```
How do I install the latest version?

**Comment by wfscheper** [comment]
Our pypi release is out of date and needs to be cleaned up. We have an 0.15.1 in the pipeline that fixes a lot of python3 support issues.

**Comment by mikewiebe** [comment]
@wfscheper Thanks for the info.  When will the 0.15.1 release be available on pypi?

**Comment by wfscheper** [comment]
I'm going to try and get it out today.

**Comment by mikewiebe** [comment]
Fantastic.  Thanks for your help.
