### ISSUE TITLE
Remote debugging fails to connect

### ISSUE THREAD

**Issue by haridsv** [sassoftware/epdb#7]
I installed latest epdb and did a test run. Had a sample file like this:

```
import epdb
epdb.serve(port=8124)
print("Hello World")
```

Started this on one terminal:

```
$ ~/python/bin/python /tmp/t.py
Starting epdb server
```

When I tried to connect to this from another terminal, it kept disconnecting:

```
$ ~/python/bin/python -c 'import epdb; epdb.connect(port=8124)'
> /tmp/t.py(3)<module>()
-> print("Hello World")
(Epdb) *** Connection closed by remote host ***
```

On the server side, I don't see any error. I even tried to put the serve call in an exception block, but there was no exception. 

When I used telnet I was able to connect:

```
 telnet localhost 8124
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
> /tmp/t.py(3)<module>()
-> print("Hello World")
(Epdb)

(Epdb)
(Epdb)
```

However, this has the issue that pressing `<CR>` ends up sending extra blank line or something like that. E.g., typing `next` ends up running it twice (the second time for the extra blank line), so this is not a very good workaround.

**Comment by wfscheper** [comment]
What versions of python have you tried? Also, can you recreate the issue if you use the default port?

**Comment by haridsv** [comment]
I have Python 2.7.5 installed on this host. I changed the port because another service was listening on that port, but I just shut it down and tried with the default port and I get the same issue.

BTW, do you know how to avoid the extra blank line that is getting sent with `<CR>` when using telnet?

**Comment by wfscheper** [comment]
I can recreate the issue with 2.7.5. I need to do more debugging to figure out exactly what's broken as the server just silently fails, but I do see that I'm getting some IO error.

Currently the best workaround I can offer is to use python 2.7.13.

**Comment by haridsv** [comment]
Thanks for the workaround, I can confirm that it works with 2.7.13. FWIW, only the server needs to be on 2.7.13 as client on 2.7.5 works too.

**Comment by sdressler** [comment]
I stumbled also over this with Python 3.6. You can use netcat (`nc <host> <port>`) instead of telnet.

**Comment by wfscheper** [comment]
@sdressler, will take a look. Can you provide the exact version of python and what environment you're running on.

**Comment by sdressler** [comment]
@wfscheper actually I was wrong with the Python version, it is Python 3.5.2. epdb runs inside a docker container and we map port 9999 to the outside. When we call `epdb.connect(port=9999)` on the *host*, the connection is closed immediately. The host runs on Python 3.6.1. What else information do you need?

**Comment by wfscheper** [comment]
~~Let me see if I can recreate the issue with what you've given me.~~

Are you using a public docker image that has 3.5.2 in it?

**Comment by sdressler** [comment]
Happy new year!

Sorry for the late reply. alpine 3.5 serves as our base image.

**Comment by wfscheper** [comment]
@sdressler, thanks for the extra info.

**Comment by wfscheper** [comment]
@sdressler, I'm not able to recreate this issue. Here's the steps I took:

1. Create t.py with contents
```
import epdb
epdb.serve(port=9999)
print("Hello World")
```
2. Run alpine container, binding port 9999 and copying in t.py
```
docker run -it -v $(pwd)/t.py:/t.py -p 9999:9999 alpine:3.5 sh
apk update && apk install python3
pip3 install epdb
python3 t.py
```
3. In another terminal, connect with epdb
```
python3.6 -m venv venv
venv/bin/pip install epdb
venv/bin/python3.6 -c 'import epdb; epdb.connect(port=9999)'
```

I get the following:
```
> /t.py(3)<module>()
-> print("Hello World")
(Epdb) n
Hello World
--Return--
> /t.py(3)<module>()->None
-> print("Hello World")
(Epdb)
--Call--
> /usr/lib/python3.5/threading.py(1273)_shutdown()
-> def _shutdown():
(Epdb)
> /usr/lib/python3.5/threading.py(1279)_shutdown()
-> tlock = _main_thread._tstate_lock
(Epdb) c
*** Connection closed by remote host ***
```

Is there anything more complicated going on in your setup that I'm missing?

**Comment by termlen0** [comment]
> I can recreate the issue with 2.7.5. I need to do more debugging to figure out exactly what's broken as the server just silently fails, but I do see that I'm getting some IO error.
> 
> Currently the best workaround I can offer is to use python 2.7.13.

Is this still the case with Python 2.7.5?

**Comment by sdressler** [comment]
@termlen0 cannot repro on Python 3.6 anymore, unfortunately not using 2.7.5.

**Comment by wfscheper** [comment]
@termlen0, unfortunately yes. This is a case where the source of the problem is not immediately obvious and the scope of the issue is limited to a very particular (and old) version of python. This is a case where someone will need to scratch their own itch. Even just isolating what exactly is causing the problem would be helpful.

**Comment by j3pic** [comment]
I'm getting this error on Python 3.7.2. I can't reproduce it with a simple Python script. It only happens when I run my employer's huge Django test suite under a code coverage tool.
